### ISSUE TITLE
"Create account" functionality is missing

### ISSUE THREAD

**Issue by Daniel-Mietchen** [petermr/contentMine#1]
The current Login button does not seem to allow to create an account, and I do not see another way to go about it in the current setup.

**Comment by petermr** [comment]
Currently we create content in the github wiki
https://github.com/petermr/contentmine ; Mark has developed a system for
transferring it to the website. If you have a github account then you can
login and edit. Or is there some other functionality we need?

P.

On Fri, Apr 25, 2014 at 9:37 PM, Daniel Mietchen
notifications@github.comwrote:

> The current Login button does not seem to allow to create an account, and
> I do not see another way to go about it in the current setup.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/petermr/contentMine/issues/1
> .

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by petermr** [comment]
Yep to edit site content for now is done by the wiki. Account stuff is not
needed at the moment, but the framework is there in case it becomes useful
to the service later. For the time being I will hide the login button from
the site.

We probably should make a contentmine organisation on github as Richard
Smith suggested, but for now the petermr/contentmine wiki will do fine.

I will get automated pulling from the wiki set up for next week too.

Mark

**Comment by Daniel-Mietchen** [comment]
OK, makes sense. I would also be interested in Mark's system to turn the GitHub wiki into the website and suggest to make it available via https://github.com/petermr/contentMine/ .

**Comment by petermr** [comment]
We probably need to explain it more on both sites.

On Fri, Apr 25, 2014 at 10:37 PM, Daniel Mietchen
notifications@github.comwrote:

> OK, makes sense. I would also be interested in Mark's system to turn the
> GitHub wiki into the website and suggest to make it available via
> https://github.com/petermr/contentMine/ .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/petermr/contentMine/issues/1#issuecomment-41442060
> .

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069
